Repository m1naworld/issueTest, pull requests merged in 2022-12, with the labels that each got.

#6 ♻️ Refactor: PR 템플릿 변경
  .github/PULL_REQUEST_TEMPLATE.md
Labels: refactor

#7 question : 이슈 연습하기
  HJ/test.js
Labels: question

#11 question : 현정 이슈
  HJ/test.js
Labels: question

#13 feat: 파일 폴더 생성
  MCHO/index.js
Labels: feature

#12 refactor : test
  subinterst.js
Labels: refactor

#17 Feater/#16
  subinterst.js
Labels: feature
